package com.example.util;

import java.util.Random;

public class GenerateRandomNumber {
	
	public static String getAutoGeneratedNumber(){
		
		Random rand = new Random();
		 
		String generatedValue = String.format("%05d", rand.nextInt(100000));
		
		return generatedValue;
		
		}

}
